[package]
name = "time-tz"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
phf = "0.10.1"
time = { version = "0.3.7", features = ["macros"] }

[build-dependencies]
parse-zoneinfo = { version = "0.3" }
phf_codegen = "0.10.0"
